version: "3.8"

services:
  geolocation_db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geolocation_network

  redis_db:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - geolocation_network

  geo_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      NODE_ENV: local
    volumes:
      - ./:/usr/app
    working_dir: /usr/app/
    depends_on:
      - geolocation_db
      - redis_db
    networks:
      - geolocation_network

volumes:
  postgres_data:

networks:
  geolocation_network:
